### PR TITLE
Favourite team feature

### PR DESCRIPTION
**Pull request by rikware**
This is a simple favourite teams feature. The user sets their favourite team via the settings and an extra top level menu item is added. This leads to a menu providing any recent games which feature that team. The games are set to always use the favourite team's announcers (possibly should make that another option).

The last 3 week's worth of games are supplied and then older games can be accessed through another submenu.

### CODE REVIEW

**Comment by maxgalbu** [comment]
Thank you! This looks pretty good, I'd ask you one thing: can you add a "None" setting to the Favourite team, so that you can remove the favourite team list item?

**Comment by rikware** [comment]
Thanks. I've added the None option and also improved how it handles when there is no favourite team selected. It will now always have the favourite team menu item at the top menu and when you select it it will bring up the settings if your favourite team is set to None.

**Comment by maxgalbu** [comment]
Thanks! Will check it soon, I'll probably release it alongside the 0.9 version

**Comment by rikware** [comment]
I was thinking of adding another top level menu as well where you can get to games broken down by team. So similar to the favourite team's menu but for all teams. Probably need a bit of refactoring to grab out some common code which I just replicated in favteam.py.

e.g. Root Menu->Games by Team->[All team names]->[all of specific team's recent games]

**Comment by maxgalbu** [comment]
Merged in 3ac72cd58d37679f11b399fe40fd02cadee1e4f6. Thanks!

**Pull request closed without merging**
