### PR TITLE
Several fixes (KeyError for 'multiCameras', not existing self.folder, thumbnails under Favorite team feature), team/franchise names fixes and improvements, Kodi v17 Krypton refreshed assets, Combined thumbnails, Improved settings

### PR DESCRIPTION
**Pull request by ivankokan**
Team names fixes/improvements & New fanart

### CODE REVIEW

**Comment by maxgalbu** [comment]
Thank you @ivankokan, let me look into it

**Comment by ivankokan** [comment]
@maxgalbu, no need to hurry! I will have some more updates this week...

**Comment by maxgalbu** [comment]
What do you have in mind?

**Comment by ivankokan** [comment]
Thumbnails displaying both logos, all missing team names for international teams, future-proof franchise mapping (e.g. so that "Pelicans" is mapped to both "nop" and "noh") that might be useful in the future etc.

**Comment by ivankokan** [comment]
Hi, @maxgalbu! Have you considered any of these bug fixes and improvements? I'm about to start working on thumbnails while we are still in the preseason.

**Comment by ivankokan** [comment]
Hi. Considering that every thumbnail of combined logos takes ~50 KB, it might take around 30 * 30 * 50 KB = 45000 KB to store all pairs on device where Kodi is installed. Is it too much? On the other hand, dynamically generating thumbnails every time might be also inefficient. What do you think, which way to go? However, which path is the right one to (temporarily) generate thumbnails in?

**Comment by maxgalbu** [comment]
I like it!

> However, which path is the right one to (temporarily) generate thumbnails in?

See the path where the shared JSON is stored: https://github.com/maxgalbu/xbmc.plugin.video.nba/blob/master/src/shareddata.py#L7-L8
You could store them there.

> On the other hand, dynamically generating thumbnails every time might be also inefficient

Yes, counting how many people use embedded systems for kodi.

**Comment by ivankokan** [comment]
Thanks! I will have two more commits, and then I leave everything to you.

**Comment by ivankokan** [comment]
Hi, @maxgalbu! I think it's better to stop at this moment so you can check and merge all these changes.

Meanwhile, I will check all missing teams and logos but under my dev branch, so this Pull request does not get messy again.

**Comment by maxgalbu** [comment]
Looks good to me, a bit slow to generate the thumbnails (macbook pro 2013), but the speed is unrecognisable after they're loaded from cache. Will merge to master right away, I'll revert just one thing: I intentionally left "username" as field in the settings, to avoid people mistakenly thinking the plugin is not working, when they actually forgot to fill again the "email" label

**Pull request merged**
